### ISSUE TITLE
"Sorry but something went wrong. We were unable to request a ride. null"

### ISSUE THREAD

**Issue by geopapyrus** [appacademy/uber_slack#25]
Does requesting a ride actually works or is it using uber's sandbox api?
I trying to order a ride and got this:

1.5x surge is in effect. Reply ​_/uber accept_​ to confirm the ride
Sorry but something went wrong. We were unable to request a ride.
null

I don't understand if this is a hackaton test project or if it actually works.
Could you guys clarify?

thanks

**Comment by EdmundLeex** [comment]
does the issue persist? it should work.

**Comment by huangchris** [comment]
Edmund, do you have access to the Raven/Sentry error logs? That message should have been because of an error raised making the confirmation request to Uber--especially with the null.

**Comment by EdmundLeex** [comment]
Nicole has it. 

Edmund Li

**Comment by ndevvy** [comment]
hey guys! looks like either Sentry isn't currently logging, or I don't have access anymore.

**Comment by EdmundLeex** [comment]
Oh, just realize the production app doesn't have sentry. It was only on staging. 

Edmund Li

**Comment by EdmundLeex** [comment]
@geopapyrus when did you add the command to your slack channel? we rewired our app back in December which may cause command added before that to stop working.

**Comment by EdmundLeex** [comment]
This is fixed.
