### ISSUE TITLE
auth failing

### ISSUE THREAD

**Issue by jesperwf** [appacademy/uber_slack#43]
Hi there, I did /uber in slack. 

Slack returned:
Hey @jesper! Looks like this is your first ride from Slack. Go here to activate.

Safari window opened and returned:
{"text":"Sorry, we encountered an error! Please let us know about what caused this at https://github.com/appacademy/uber_slack/issues. If you requested a pickup, enter _/uber status_ to see if the request went through."}

**Comment by EdmundLeex** [comment]
looks like we ran out of memory on heroku. we scaled it up. please let us know if the issue persist. 

closing this issue
