### ISSUE TITLE
Handle all 500 errors with a nice apology to the user.

### ISSUE THREAD

**Issue by 7imon7ays** [appacademy/uber_slack#5]
E.g. "Sorry. Something went wrong on our end."

**Comment by EdmundLeex** [comment]
@edhuang24 and @ndevvy fixed this

**Comment by EdmundLeex** [comment]
`/uber products` not caught. invalid address not caught
`/uber ride` invalid addresses are not caught

**Comment by ndevvy** [comment]
Known `/uber products` and `/uber ride` and unknown command errors are now rendered as friendly messages.  `/uber get_eta` errors not handled yet

**Comment by EdmundLeex** [comment]
`/uber` without any params
